### PR TITLE
fix(security): https protocol mapping

### PR DESCRIPTION
**Pull request by Engineering-Excellence**

### CODE REVIEW

**Review by bnbu — APPROVED** [review]
LGTM

**Review by grandfark — APPROVED** [review]
ACK

**Comment by bnbu** [comment]
must uncomment this code in server.xml of tomcat

    <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
               maxThreads="150" SSLEnabled="true"
               maxParameterCount="1000"
               >
        <SSLHostConfig>
            <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>

**Review by jiyeon-git — APPROVED** [review]
ack

**Pull request merged**
